#ifndef COMMANDS_H
#define COMMANDS_H
#include <stdint.h>

enum class Command : uint8_t
{
    PING,
    READ_SUCCESS,
    READ_FAILURE,
    START,
    STOP,
    RESET,
    STOP_ALL_BROADCAST,
    RESTORE_ALL_BROADCAST,

    SET_MOTOR_DATA,
    GET_MOTOR_DATA,
    SET_CONTROLLER_PROPERTIES,
    GET_CONTROLLER_PROPERTIES,
    INIT_MOTORS,

    GET_PID_CONSTANTS,
    SET_PID_CONSTANTS,
    SET_MOTOR_PWMS,
    GET_MOTOR_PWMS,
    SET_MOTOR_SPEED_SETPOINTS,
    SET_MOTOR_ANGLE_SETPOINTS,

    GET_MOTOR_SPEED,
    GET_MOTOR_ANGLE,
    SET_MOTOR_CONTROL_MODES,
    GET_MOTOR_CONTROL_MODES,
    SET_ODO_BROADCAST_STATUS,
    SEND_ODO_SPEEDS,
    SEND_ODO_ANGLES,
    SEND_ODO_PWMS,

};

#endif // COMMANDS_H